# Generated by Django 3.1.3 on 2020-11-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0003_auto_20201121_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miniapp.customer', verbose_name='Владелец'),
        ),
    ]
