# Generated by Django 3.1.3 on 2020-11-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0005_auto_20201121_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
    ]
